gateway:
    resource: "@BatnaArchiSiebelBundle/Resources/config/routing/gateway.yml"
    prefix:   /gtw
    
siebelserver:
    resource: "@BatnaArchiSiebelBundle/Resources/config/routing/siebelserver.yml"
    prefix:   /ss

enterpriseserver:
    resource: "@BatnaArchiSiebelBundle/Resources/config/routing/enterpriseserver.yml"
    prefix:   /es

host:
    resource: "@BatnaArchiSiebelBundle/Resources/config/routing/host.yml"
    prefix:   /host

env:
    resource: "@BatnaArchiSiebelBundle/Resources/config/routing/environnement.yml"
    prefix:   /env

contexte:
    resource: "@BatnaArchiSiebelBundle/Resources/config/routing/contexte.yml"
    prefix:   /contxt

bdd:
    resource: "@BatnaArchiSiebelBundle/Resources/config/routing/bdd.yml"
    prefix:   /bdd

