parameters:
#    batna_archi_siebel.example.class: Batna\Bundle\ArchiSiebelBundle\Example

services:
#    batna_archi_siebel.example:
#        class: %batna_archi_siebel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
