<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class BatnaBundleArchiSiebelBundleEntityGatewayProxy extends \Batna\Bundle\ArchiSiebelBundle\Entity\Gateway implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setPort($port)
    {
        $this->__load();
        return parent::setPort($port);
    }

    public function getPort()
    {
        $this->__load();
        return parent::getPort();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setHost($host)
    {
        $this->__load();
        return parent::setHost($host);
    }

    public function getHost()
    {
        $this->__load();
        return parent::getHost();
    }

    public function setEnvironnement($environnement)
    {
        $this->__load();
        return parent::setEnvironnement($environnement);
    }

    public function getEnvironnement()
    {
        $this->__load();
        return parent::getEnvironnement();
    }

    public function setBdd($bdd)
    {
        $this->__load();
        return parent::setBdd($bdd);
    }

    public function getBdd()
    {
        $this->__load();
        return parent::getBdd();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'port', 'description', 'host', 'environnement', 'bdd');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}