parameters:
#    batna_user.example.class: Batna\Bundle\UserBundle\Example

services:
#    batna_user.example:
#        class: %batna_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
